openapi: 3.0.0
info:
  title: API de Contatos
  description: Aplicação para gerenciamento de contatos de pessoas e organizações
  contact:
    name: Rommel Carneiro
    email: rommelcarneiro@servidor.net
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/rommelcarneiro/APIContatos/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://virtserver.swaggerhub.com/rommelcarneiro/APIContatos/1.0.0-oas3
- url: http://localhost:5500
  description: Servidor Local
paths:
  /pessoas:
    summary: Manipular informações relacionadas às pessoas da aplicação
    get:
      tags:
      - Pessoas
      summary: Listar pessoas cadastradas
      description: 'Retorna um array de pessoas '
      operationId: listaPessoas
      parameters:
      - name: search
        in: query
        description: Texto a ser procurado no nome das pessoas
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: order
        in: query
        description: Critério de ordenação dos resultados (ascendente | descedente)
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - asc
          - desc
      - name: tags
        in: query
        description: Tags a serem procuradas nas pessoas cadastradas
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pessoa'
                x-content-type: application/json
      x-swagger-router-controller: Pessoas
    post:
      tags:
      - Pessoas
      summary: Cadastrar uma pessoa
      description: ""
      operationId: inserePessoa
      requestBody:
        description: Pessoa a ser inserida
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pessoa'
      responses:
        "201":
          description: Recurso inserido com sucesso
      x-swagger-router-controller: Pessoas
  /pessoas/{idPessoa}:
    get:
      tags:
      - Pessoas
      summary: Obter uma pessoa específica por meio do ID
      operationId: listaPessoaPorId
      parameters:
      - name: idPessoa
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pessoa'
        "404":
          description: Pessoa não encontrada
      x-swagger-router-controller: Pessoas
    put:
      tags:
      - Pessoas
      summary: Alterar uma pessoa específica por meio do ID
      operationId: alteraPessoa
      parameters:
      - name: idPessoa
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: Recurso alterado com sucesso
        "400":
          description: Erro ao alterar o recurso no servidor
      x-swagger-router-controller: Pessoas
    delete:
      tags:
      - Pessoas
      summary: Alterar uma pessoa específica por meio do ID
      operationId: pessoasIdPessoaDELETE
      parameters:
      - name: idPessoa
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "204":
          description: Recurso excluído com sucesso
        "400":
          description: Erro ao excluir o recurso no servidor
      x-swagger-router-controller: Pessoas
  /pessoas/{tag}:
    get:
      tags:
      - Pessoas
      summary: Listar pessoas cadastradas
      description: ""
      operationId: listaPessoasPorTag
      parameters:
      - name: tag
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Operação bem sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pessoa'
                x-content-type: application/json
      x-swagger-router-controller: Pessoas
components:
  schemas:
    Pessoa:
      required:
      - email
      - nome
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
          description: Nome da referida pessoa
        email:
          type: string
          description: Endereço eletrônico da pessoa
        telefone:
          type: string
          description: Endereço eletrônico da pessoa
        Organizacao:
          $ref: '#/components/schemas/Organizacao'
        tags:
          type: array
          items:
            type: string
      example:
        id: 5
        nome: Francis Ford Copolla
        email: copolla@hollywood.com
        telefone: 001-124-2111
        tags:
        - cinema
        - trabalho
    Organizacao:
      title: Organizacao
      required:
      - nome
      - segmento
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        segmento:
          type: string
        endereco:
          type: string
        cidade:
          type: string
        cep:
          type: string
        estado:
          type: string
        telefones:
          type: array
          items:
            type: string
      example:
        id: 1
        nome: Acme Corporation
        segmento: Varejo
        endereco: "Av. Rebolças, 422 - Centro"
        cidade: São Paulo
        cep: 33422-990
        estado: SP
        telefones:
        - 11-3234-5543
        - 11-4425-5544
